package com.runner;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import net.masterthought.cucumber.Configuration;
import net.masterthought.cucumber.ReportBuilder;

public class JVMReport {
	public static void generateJVMReport(String jsonLoc) {
		File jvmPath = new File("C:\\Users\\god\\eclipse-workspace\\Online7.30AM28thMarCucumber\\target");
		List<String> li = new ArrayList<String>();
		li.add(jsonLoc);

		Configuration con = new Configuration(jvmPath, "Facebook Report");
		con.addClassifications("OS", "Windows");
		con.addClassifications("Browser", "Chrome");
		con.addClassifications("Version", "90 above");
		con.addClassifications("Generated By", "XXXXXX");

		ReportBuilder builder = new ReportBuilder(li, con);
		builder.generateReports();

	}

}
